# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in diff_solver.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "standard", "~> 1.3"

gem "telegram-bot-ruby", "~> 2.7", groups: [:development, :test]
gem "dotenv", "~> 3.2", groups: [:development, :test]
